// Runs in the trusted host realm. Guest bypass checks separately bind real bridges.
globalThis.testAuthority = () => {
  const checks=[], ok=(v,n)=>{if(!v)throw Error(n);checks.push(n);};
  const fails=(fn,pattern,n)=>{let e;try{fn();}catch(x){e=x.message;}ok(e && e.includes(pattern),n);};
  let a=new ExecutionAuthority();
  fails(()=>a.define('x',undefined),'explicit','explicit mode');
  a.define('x','shared',0);a.define('y','shared',0);
  let first=a.begin('x'), second=a.begin('x');
  ok(first.start && !second.start && first.task===second.task,'shared producer');
  a.cancel(first.lease);ok(a.outcome(first.lease).error==='cancelled','reader cancellation');
  ok(a.snapshot(second.task)===0,'remaining reader survives');
  a.cancel(second.lease);fails(()=>a.check(second.task),'cancelled','last reader cancels');
  a.settle(second.task,99);ok(a.outcome(second.lease).error==='cancelled','cancelled publication');
  let suspended=a.begin('x'), setter=a.begin('x','write');
  a.commit(setter.task,2);a.settle(setter.task,2);
  fails(()=>a.commit(suspended.task,3),'stale','stale commit');
  a.settle(suspended.task,3);ok(a.outcome(suspended.lease).error==='stale evaluation','stale publication');
  let fresh=a.begin('x');ok(a.snapshot(fresh.task)===2,'explicit fresh read');
  fails(()=>a.commit(fresh.task,Promise.resolve(3)),'JSON','no async update');
  fails(()=>a.commit(fresh.task,{get bad(){throw Error('invoked');}}),'JSON','no accessor update');
  fails(()=>a.begin('x','read',fresh.task),'cycle','direct cycle');
  let child=a.begin('y','read',fresh.task);
  fails(()=>a.begin('x','read',child.task),'cycle','indirect cycle');
  a.cancel(fresh.lease);fails(()=>a.check(child.task),'cancelled','owned dependency cancellation');
  a.settle(fresh.task);a.settle(child.task);
  a=new ExecutionAuthority();a.define('x','shared');a.define('y','shared');
  let x=a.begin('x'), y=a.begin('y');a.begin('y','read',x.task);
  fails(()=>a.begin('x','read',y.task),'cycle','concurrent root cycle');
  a.cancel(x.lease);ok(a.check(y.task).id===y.task,'shared child survives');
  a.settle(x.task);a.settle(y.task);
  a=new ExecutionAuthority();a.define('x','independent',0);
  x=a.begin('x');y=a.begin('x');ok(x.task!==y.task && y.start,'independent reads');
  a.cancel(x.lease);fails(()=>a.check(x.task),'cancelled','skip cancelled before start');
  a.commit(y.task,7);a.cancel(y.lease);
  let z=a.begin('x');ok(a.snapshot(z.task)===7,'prior mutation survives');
  a.define('x','independent',10);fails(()=>a.check(z.task),'stale','definition fences continuation');
  for(const t of [x,y,z])a.settle(t.task);
  ok(a.stats().tasks===0 && a.stats().readers===0,'cleanup');
  return checks;
};
