// Live browser qualification. Requires a temporary LelloAuth viewer, never a real user's password.
import fs from 'node:fs';import {createRequire} from 'node:module';const require=createRequire(import.meta.url);const {chromium}=require('../spikes/runtime/node_modules/playwright');
const origin='https://talia.lan.lelloman.com',issuer='https://auth.lelloman.com';
const user=JSON.parse(fs.readFileSync('.local/access-verification/user.json','utf8'));
const token=fs.readFileSync('.local/deployment/operator.token','utf8').trim();
const owner=issuer+'#67940ca6-9d1e-4ca2-af0b-a71b9d09bda2',subject=issuer+'#'+user.id;
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});let changed=false,old,revision,phase='initialize';const checks=[];
async function mcp(name,args={}){const r=await fetch(origin+'/agent',{method:'POST',headers:{Authorization:'Bearer '+token,'Content-Type':'application/json'},body:JSON.stringify({name,arguments:args})});if(!r.ok)throw Error('operator request failed');const v=await r.json();if(v.error)throw Error('operator rejected');return v;}
async function share(viewers,expected){return mcp('dashboard_access_set',{dashboardId:'monitor',owner:old?.owner||owner,public:old?.public||false,viewers,expectedRevision:expected,requestId:crypto.randomUUID()});}
async function login(context){const page=await context.newPage();await page.goto(origin);await page.getByRole('link',{name:'Sign in with LelloAuth'}).click();const until=Date.now()+40000;let submitted=false;while(Date.now()<until){if(new URL(page.url()).origin===origin&&(await page.locator('#account-role').textContent().catch(()=>null))==='Viewer')return page;if(new URL(page.url()).origin===issuer){if(!submitted&&await page.locator('input[name=username]').isVisible()){await page.locator('input[name=username]').fill(user.username);await page.locator('input[name=password]').fill(user.password);await page.locator('button[type=submit]').click();submitted=true;}else if(await page.locator('button[value=allow]').isVisible())await page.locator('button[value=allow]').click();}await page.waitForTimeout(100);}throw Error('login incomplete');}
try{
 phase='viewer login';const context=await browser.newContext(),page=await login(context);await page.getByRole('heading',{name:'No dashboards available yet'}).waitFor();checks.push('new LelloAuth user is a viewer with no private dashboard access');
 phase='MCP sharing';const policies=await mcp('dashboard_access_list');old=policies.dashboards.find(d=>d.dashboardId==='monitor');const saved=await share([...(old?.viewers||[]),subject],old?.revision||0);revision=saved.revision;changed=true;
 await page.locator('#refresh-dashboards').click();await page.getByText('Talìa is online',{exact:true}).waitFor();await page.waitForFunction(()=>window.dashboardReport?.registration?.connected);checks.push('MCP sharing delivers the saved welcome dashboard');
 phase='viewer enforcement';const results=await page.evaluate(async()=>{const send=async body=>(await(await fetch('/engine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:1,epoch:1,client:'probe',dashboard:window.taliaDashboard,...body})})).json());return Promise.all([{op:'hello'}, {op:'read',args:{id:'deployment-check'}},{op:'write',args:{id:'deployment-check'}},{op:'monitoringConfig'}].map(send));});if(results[0].value.values.length!==0||results.slice(1).some(v=>v.error!=='forbidden'))throw Error('viewer boundary failed');checks.push('viewer snapshots exclude unrelated metrics; direct reads, writes and configuration rejected');
 phase='account default';await page.locator('#make-default').click();await page.getByText('New clients will open this dashboard automatically.',{exact:true}).waitFor();const another=await browser.newContext();const second=await login(another);await second.getByText('Talìa is online',{exact:true}).waitFor();await second.waitForFunction(()=>window.dashboardReport?.registration?.connected);checks.push('account default opens automatically in another browser installation');
 phase='revocation';const restored=await share(old?.viewers||[],revision);revision=restored.revision;changed=false;await page.getByRole('heading',{name:'No dashboards available yet'}).waitFor({timeout:15000});checks.push('unsharing removes active viewer access');
 const report={passed:true,checkedAt:new Date().toISOString(),origin,checks};fs.writeFileSync('.local/access-verification/live.json',JSON.stringify(report,null,2)+'\n',{mode:0o600});console.log(JSON.stringify(report));
}catch(e){console.error('Access qualification failed during '+phase+': '+e.name);process.exitCode=1;}finally{if(changed){try{await share(old?.viewers||[],revision);}catch{console.error('Temporary share needs cleanup');process.exitCode=1;}}await browser.close();}
