// Real browser + actual Rust service, with a local OIDC provider (test binary only).
import {chromium} from '../../spikes/runtime/node_modules/playwright/index.mjs';
import {spawn,execFileSync} from 'node:child_process';import {once} from 'node:events';
import {mkdirSync,mkdtempSync,writeFileSync,readFileSync,rmSync} from 'node:fs';import os from 'node:os';import path from 'node:path';import http from 'node:http';import https from 'node:https';import crypto from 'node:crypto';import assert from 'node:assert/strict';
const tmp=mkdtempSync(path.join(os.tmpdir(),'talia-access-'));let engine,browser,proxy,provider;
try{
 execFileSync('openssl',['req','-x509','-newkey','rsa:2048','-nodes','-keyout',tmp+'/tls.key','-out',tmp+'/tls.crt','-days','1','-subj','/CN=localhost','-addext','subjectAltName=DNS:localhost'],{stdio:'ignore'});
 const keys=crypto.generateKeyPairSync('rsa',{modulusLength:2048}),jwk={...keys.publicKey.export({format:'jwk'}),kid:'fixture',use:'sig',alg:'RS256'};
 let issuer,origin,port;const codes=new Map(),tokens=new Map();
 const json=(res,v)=>{res.setHeader('Content-Type','application/json');res.end(JSON.stringify(v));};
 provider=http.createServer(async(req,res)=>{
  const u=new URL(req.url,issuer);if(u.pathname==='/.well-known/openid-configuration')return json(res,{issuer,authorization_endpoint:issuer+'/authorize',token_endpoint:issuer+'/token',jwks_uri:issuer+'/jwks',introspection_endpoint:issuer+'/introspect',response_types_supported:['code'],id_token_signing_alg_values_supported:['RS256'],code_challenge_methods_supported:['S256'],token_endpoint_auth_methods_supported:['none','client_secret_basic']});
  if(u.pathname==='/jwks')return json(res,{keys:[jwk]});
  if(u.pathname==='/authorize'){const user=(req.headers.cookie||'').includes('fixture_admin=1')?'admin':'viewer';const code=crypto.randomUUID();codes.set(code,{user,nonce:u.searchParams.get('nonce'),challenge:u.searchParams.get('code_challenge')});const redirect=new URL(u.searchParams.get('redirect_uri'));redirect.searchParams.set('code',code);redirect.searchParams.set('state',u.searchParams.get('state'));res.writeHead(302,{Location:redirect.href});return res.end();}
  const chunks=[];for await(const c of req)chunks.push(c);const form=new URLSearchParams(Buffer.concat(chunks).toString());
  if(req.headers.authorization!=='Basic '+Buffer.from('talia:fixture-secret-with-at-least-thirty-two-characters').toString('base64')){res.statusCode=401;return res.end();}
  if(u.pathname==='/token'){const c=codes.get(form.get('code'));codes.delete(form.get('code'));if(!c||crypto.createHash('sha256').update(form.get('code_verifier')||'').digest('base64url')!==c.challenge){res.statusCode=400;return res.end();}const now=Math.floor(Date.now()/1000),payload={iss:issuer,sub:c.user,aud:'talia',iat:now,exp:now+3600,nonce:c.nonce,name:c.user};const input=Buffer.from(JSON.stringify({alg:'RS256',kid:'fixture'})).toString('base64url')+'.'+Buffer.from(JSON.stringify(payload)).toString('base64url');const token=crypto.randomUUID();tokens.set(token,c.user);return json(res,{access_token:token,token_type:'Bearer',id_token:input+'.'+crypto.sign('RSA-SHA256',Buffer.from(input),keys.privateKey).toString('base64url')});}
  if(u.pathname==='/introspect'){const sub=tokens.get(form.get('token'));return json(res,{active:!!sub,sub,iss:issuer,client_id:'talia'});}res.statusCode=404;res.end();
 });provider.listen(0,'127.0.0.1');await once(provider,'listening');issuer='http://127.0.0.1:'+provider.address().port;
 proxy=https.createServer({key:readFileSync(tmp+'/tls.key'),cert:readFileSync(tmp+'/tls.crt')},(req,res)=>{const upstream=http.request({hostname:'127.0.0.1',port,path:req.url,method:req.method,headers:req.headers},r=>{res.writeHead(r.statusCode,r.headers);r.pipe(res);});upstream.on('error',()=>{res.statusCode=503;res.end();});req.pipe(upstream);});proxy.listen(0,'127.0.0.1');await once(proxy,'listening');origin='https://localhost:'+proxy.address().port;
 writeFileSync(tmp+'/secret','fixture-secret-with-at-least-thirty-two-characters');execFileSync('python3',['deploy/package-web.py',tmp+'/web']);
 engine=spawn('cargo',['test','--manifest-path','engine/Cargo.toml','--offline','--bin','talia-engine','browser_fixture_service','--','--ignored','--nocapture'],{env:{...process.env,TALIA_TEST_DB:tmp+'/engine.db',TALIA_OIDC_ISSUER:issuer,TALIA_OIDC_CLIENT_ID:'talia',TALIA_OIDC_SECRET_FILE:tmp+'/secret',TALIA_PUBLIC_ORIGIN:origin,TALIA_AUTH_DB:tmp+'/auth.db',TALIA_WEB_ROOT:tmp+'/web',TALIA_BOOTSTRAP_ADMINS:issuer+'#admin'},detached:true,stdio:['ignore','pipe','pipe']});
 await new Promise((resolve,reject)=>{let out='';const timeout=setTimeout(()=>reject(Error('service startup timeout')),60000);engine.stdout.on('data',d=>{out+=d;const m=out.match(/\{"incarnation":"[^"]+","port":(\d+)\}/);if(m){port=Number(m[1]);clearTimeout(timeout);resolve();}});engine.stderr.on('data',d=>process.stderr.write(d));engine.on('exit',code=>{clearTimeout(timeout);reject(Error('service exited '+code));});});
 browser=await chromium.launch({headless:true});const admin=await browser.newContext({ignoreHTTPSErrors:true}),viewer=await browser.newContext({ignoreHTTPSErrors:true});await admin.addCookies([{name:'fixture_admin',value:'1',url:issuer}]);
 async function login(context){const p=await context.newPage();await p.goto(origin);await p.getByRole('link',{name:'Sign in with LelloAuth'}).click();await p.waitForFunction(()=>['Administrator','Viewer'].includes(document.querySelector('#account-role')?.textContent));return p;}
 const a=await login(admin),v=await login(viewer);await v.getByRole('heading',{name:'No dashboards available yet'}).waitFor();assert.equal(await v.locator('#sharing').isVisible(),false);
 const api=(p,body)=>p.evaluate(async body=>(await(await fetch('/account',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)})).json()),body);
 assert.equal((await api(v,{op:'role',subject:issuer+'#viewer',admin:true})).error,'forbidden');
 await a.waitForFunction(()=>window.dashboardReport?.registration?.connected);await a.locator('#sharing summary').click();await a.locator('#share-public').check();await a.locator('#save-sharing').click();await a.getByText('Dashboard sharing saved.',{exact:true}).waitFor();
 await v.locator('#refresh-dashboards').click();await v.waitForFunction(()=>window.dashboardReport?.registration?.connected&&window.dashboardReport.state.history.length>0);assert.equal(await v.evaluate(()=>window.taliaViewer),true);
 await v.locator('#make-default').click();await v.getByText('New clients will open this dashboard automatically.',{exact:true}).waitFor();
 const catalog=await api(v,{op:'catalog'});assert.equal(catalog.defaultDashboard,'monitor');assert.deepEqual(catalog.dashboards,[{id:'monitor'}]);
 const engineCall=(p,op,args)=>p.evaluate(async({op,args})=>(await(await fetch('/engine',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:1,epoch:1,client:'probe',op,args,dashboard:window.taliaDashboard})})).json()),{op,args});
 assert.equal((await engineCall(v,'write',{id:'value'})).error,'forbidden');assert.equal((await engineCall(v,'monitoringConfig',{})).error,'forbidden');
 const another=await browser.newContext({ignoreHTTPSErrors:true});const v2=await login(another);await v2.waitForFunction(()=>window.dashboardReport?.registration?.connected);assert.equal(await v2.evaluate(()=>window.taliaDashboard.id),'monitor');
 await v.setViewportSize({width:390,height:844});assert.equal(await v.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);mkdirSync('.local/access-verification',{recursive:true});await v.screenshot({path:'.local/access-verification/viewer-mobile.png',fullPage:true});await a.screenshot({path:'.local/access-verification/admin-desktop.png',fullPage:true});
 // Session and account selection survive page reload.
 await v.reload();await v.waitForFunction(()=>window.dashboardReport?.registration?.connected);assert.equal(await v.evaluate(()=>window.taliaDashboard.id),'monitor');
 await a.locator('#share-public').uncheck();await a.locator('#save-sharing').click();await a.getByText('Dashboard sharing saved.',{exact:true}).waitFor();await v.getByRole('heading',{name:'No dashboards available yet'}).waitFor({timeout:15000});
 assert.equal((await engineCall(v,'hello',{})).error,'forbidden');assert.equal((await api(v,{op:'catalog'})).defaultDashboard,null);
 console.log(JSON.stringify({passed:true,checks:['real OIDC boundary with local provider','viewer starts empty','admin shares from shell','viewer loads public dashboard','server rejects writes and config','account default opens on new installation','reload retains selection','mobile layout fits viewport','unsharing blocks active viewer']}));
}finally{await browser?.close();if(engine?.pid){try{process.kill(-engine.pid,'SIGTERM');}catch{}}proxy?.close();provider?.close();rmSync(tmp,{recursive:true,force:true});}
