import {chromium} from '../../spikes/runtime/node_modules/playwright/index.mjs';
import {spawn,execFileSync} from 'node:child_process';import {once} from 'node:events';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const temp=await mkdtemp(path.join(os.tmpdir(),'talia-delivery-')),db=path.join(temp,'engine.db'),bin=process.env.TALIA_ENGINE_BIN||'/tmp/talia-p3-target/debug/talia-engine',fixture=process.env.TALIA_DELIVERY_FIXTURE||'/tmp/talia-p3-target/debug/examples/delivery_fixture';let engine,server,browser,enginePort=0;
async function startEngine(){engine=spawn(bin,[db,String(enginePort),'--seed'],{stdio:['ignore','pipe','inherit']});enginePort=JSON.parse(String((await once(engine.stdout,'data'))[0])).port;}
async function stopEngine(){engine.kill('SIGTERM');await once(engine,'exit');}
async function edit(action){await stopEngine();execFileSync(fixture,[db,action]);await startEngine();}
async function wait(p){await p.waitForFunction(()=>window.dashboardReport?.registration?.connected&&dashboardReport.state?.history?.length>0);}
try{
 await startEngine();await edit('second');server=spawn('python3',['dashboard/serve.py','0'],{env:{...process.env,TALIA_ENGINE_DB:db,TALIA_ENGINE_PORT:String(enginePort)},stdio:['ignore','pipe','inherit']});const port=JSON.parse(String((await once(server.stdout,'data'))[0])).port;
 browser=await chromium.launch({headless:true});const context=await browser.newContext();const a=await context.newPage();await a.goto(`http://127.0.0.1:${port}`);await wait(a);const b=await context.newPage();await b.goto(`http://127.0.0.1:${port}`);await wait(b);
 assert.equal(await a.evaluate(()=>dashboardReport.registration.clientId),await b.evaluate(()=>dashboardReport.registration.clientId));
 assert.match(await a.evaluate(()=>dashboardReport.revision),/^catalog-/);assert.equal((await a.request.get(`http://127.0.0.1:${port}/dashboard/package.json`)).status(),404);
 await a.evaluate(()=>talia.selectDashboard('monitor',{sidebar:true,label:'A'},{scale:1.25}));await a.waitForFunction(()=>dashboardReport.client.params.label==='A'&&dashboardReport.client.scale===1.25);assert.equal(await b.evaluate(()=>dashboardReport.client.params.label),undefined);
 await b.evaluate(()=>talia.selectDashboard('secondary',{sidebar:false,label:'B'}));await b.waitForFunction(()=>dashboardReport.client.dashboardId==='secondary'&&dashboardReport.client.params.label==='B');
 await a.getByRole('button',{name:'Controls',exact:true}).click();await a.getByRole('button',{name:'Apply value',exact:true}).click();await a.waitForFunction(()=>dashboardReport.actions.some(x=>x.status==='complete'));await a.evaluate(()=>talia.live('void 0'));const old=await a.evaluate(()=>({revision:dashboardReport.revision,live:talia.registration().liveInstanceId}));
 await edit('update');await a.evaluate(()=>talia.checkUpdates());await a.getByText('Update available',{exact:true}).waitFor();await b.evaluate(()=>talia.checkUpdates());await b.getByText('Update available',{exact:true}).waitFor();assert.equal(await a.evaluate(()=>dashboardReport.revision),old.revision);assert.equal(await a.evaluate(()=>dashboardReport.dirty),true);
 await a.evaluate(()=>talia.reload());await a.waitForFunction(()=>!dashboardReport.dirty&&dashboardReport.state.history.includes(25));assert.notEqual(await a.evaluate(()=>dashboardReport.revision),old.revision);assert.notEqual(await a.evaluate(()=>talia.registration().liveInstanceId),old.live);assert.equal(await a.evaluate(()=>dashboardReport.subscriptions),1);await a.getByText('Saved shared update',{exact:true}).waitFor();assert.equal(await a.evaluate(()=>dashboardReport.client.params.label),'A');assert.equal(await b.evaluate(()=>dashboardReport.client.params.label),'B');
 // A desired assignment edit never changes a running instance, and stale confirmations fail.
 await a.evaluate(async()=>{const registration=JSON.parse(localStorage.getItem('talia.registration.v1')),s=JSON.parse(sessionStorage.getItem('talia.slot.v1'));const send=async body=>(await(await fetch('/clients',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+registration.credential},body:JSON.stringify(body)})).json());const current=(await send({op:'openSlot',slot:s.id,owner:s.owner})).value;const selected=await send({op:'select',slot:s.id,owner:s.owner,expected:current.revision,assignment:{dashboardId:'monitor',params:{label:'changed'},presentation:{}}});if(selected.error)throw Error(selected.error);const stale=await send({op:'confirmDelivery',slot:s.id,owner:s.owner,revision:current.revision});if(stale.error!=='conflict')throw Error('stale assignment accepted');});assert.equal(await a.evaluate(()=>dashboardReport.client.params.label),'A');
 await stopEngine();await a.waitForFunction(()=>dashboardReport.connection==='disconnected',{},{timeout:15000});await a.evaluate(()=>talia.reload());await a.waitForFunction(()=>dashboardReport.cachedBaseline&&!dashboardReport.dirty);assert.equal(await a.evaluate(()=>dashboardReport.client.params.label),'A');assert.equal(await b.evaluate(()=>dashboardReport.client.params.label),'B');
 await startEngine();await a.evaluate(()=>talia.reload());await a.waitForFunction(()=>dashboardReport.client.params.label==='changed'&&!dashboardReport.cachedBaseline);
 const live=await a.evaluate(()=>talia.registration().liveInstanceId);await edit('delete');await assert.rejects(()=>a.evaluate(()=>talia.reload()),/not_found/);assert.equal(await a.evaluate(()=>talia.registration().liveInstanceId),live);assert.equal(await a.evaluate(()=>dashboardReport.failure),null);
 await b.reload();await wait(b);assert.equal(await b.evaluate(()=>dashboardReport.client.dashboardId),'secondary');assert.equal(await b.evaluate(()=>dashboardReport.client.params.label),'B');
 console.log(JSON.stringify({passed:true,checks:['server catalog delivery without generated files','independent tab assignments/parameters','saved shared changes notify without adoption','reload clears edits and releases old subscription','committed server effects retained','stale assignment confirmation rejected','scoped offline baseline retained','online reload adopts desired parameters','deleted dashboard preserves live instance but cannot reload','selection survives page recreation']}));
}catch(e){for(const c of browser?.contexts()||[])for(const p of c.pages())console.error(await p.evaluate(()=>({error:document.querySelector('#diagnostic')?.textContent,report:window.dashboardReport})));throw e;}
finally{await browser?.close();if(server){server.kill('SIGTERM');await once(server,'exit');}if(engine?.exitCode===null){engine.kill('SIGTERM');await once(engine,'exit');}await rm(temp,{recursive:true,force:true});}
