import {chromium} from '../../spikes/runtime/node_modules/playwright/index.mjs';
import {spawn,execFileSync} from 'node:child_process';import {once} from 'node:events';import {mkdtemp,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const temp=await mkdtemp(path.join(os.tmpdir(),'talia-registration-'));let engine,server,browser,enginePort=0;
async function startEngine(){engine=spawn(process.env.TALIA_ENGINE_BIN||'/tmp/talia-p3-target/debug/talia-engine',[path.join(temp,'engine.db'),String(enginePort),'--seed'],{stdio:['ignore','pipe','inherit']});enginePort=JSON.parse(String((await once(engine.stdout,'data'))[0])).port;}
async function wait(page){await page.waitForFunction(()=>window.dashboardReport?.registration?.connected&&dashboardReport.state?.history?.length>0);}
async function status(page){return page.evaluate(async()=>{const {credential}=JSON.parse(localStorage.getItem('talia.registration.v1'));return (await(await fetch('/clients',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+credential},body:JSON.stringify({op:'status'})})).json()).value;});}
try{
 execFileSync(process.env.TALIA_DELIVERY_FIXTURE||'/tmp/talia-p3-target/debug/examples/delivery_fixture',[path.join(temp,'engine.db'),'second']);await startEngine();server=spawn('python3',['dashboard/serve.py','0'],{env:{...process.env,TALIA_ENGINE_DB:path.join(temp,'unused'),TALIA_ENGINE_PORT:String(enginePort)},stdio:['ignore','pipe','inherit']});const port=JSON.parse(String((await once(server.stdout,'data'))[0])).port;
 browser=await chromium.launch({headless:true});const context=await browser.newContext();const a=await context.newPage();await a.goto(`http://127.0.0.1:${port}`);await wait(a);const first=await a.evaluate(()=>talia.registration());
 const popup=context.waitForEvent('page');await a.evaluate(()=>window.open(location.href));const b=await popup;await wait(b);const second=await b.evaluate(()=>talia.registration());assert.equal(first.clientId,second.clientId);assert.notEqual(first.slotId,second.slotId);assert.notEqual(first.liveInstanceId,second.liveInstanceId);
 await b.evaluate(()=>talia.selectDashboard('secondary'));await b.waitForFunction(()=>dashboardReport?.client?.dashboardId==='secondary'&&dashboardReport.registration.connected);assert.equal(await a.evaluate(()=>dashboardReport.client.dashboardId),'monitor');
 const before=await b.evaluate(()=>talia.registration());await b.reload();await b.waitForFunction(()=>window.dashboardReport?.client?.dashboardId==='secondary'&&dashboardReport.registration.connected);const after=await b.evaluate(()=>talia.registration());assert.equal(after.clientId,before.clientId);assert.equal(after.slotId,before.slotId);assert.notEqual(after.liveInstanceId,before.liveInstanceId);
 await a.evaluate(()=>talia.live('void 0'));await a.waitForFunction(()=>dashboardReport.dirty&&dashboardReport.editRevision===1);await a.waitForFunction(async()=>{const {credential}=JSON.parse(localStorage.getItem('talia.registration.v1'));const r=await(await fetch('/clients',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+credential},body:JSON.stringify({op:'status'})})).json();return r.value.slots.find(s=>s.slotId===talia.registration().slotId)?.report.dirty;});
 await a.evaluate(()=>talia.renameClient('Kitchen tablet'));assert.equal((await status(b)).name,'Kitchen tablet');
 const live=await a.evaluate(()=>talia.registration().liveInstanceId);engine.kill('SIGTERM');await once(engine,'exit');await startEngine();await a.waitForFunction(()=>!talia.registration().connected);await a.waitForFunction(()=>talia.registration().connected,{},{timeout:20000});assert.equal(await a.evaluate(()=>talia.registration().liveInstanceId),live);assert.equal((await status(a)).slots.find(s=>s.liveInstanceId===live).report.dirty,true);
 await a.evaluate(()=>{Object.defineProperty(document,'hidden',{configurable:true,get:()=>true});document.dispatchEvent(new Event('visibilitychange'));});
 await a.waitForFunction(async()=>{const {credential}=JSON.parse(localStorage.getItem('talia.registration.v1'));const r=await(await fetch('/clients',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+credential},body:JSON.stringify({op:'status'})})).json();return r.value.slots.find(s=>s.slotId===talia.registration().slotId)?.report.lifecycle==='paused';});
 await b.close();await a.waitForFunction(async()=>{const {credential}=JSON.parse(localStorage.getItem('talia.registration.v1'));const r=await(await fetch('/clients',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+credential},body:JSON.stringify({op:'status'})})).json();return r.value.slots.some(s=>s.slotId!==talia.registration().slotId&&!s.connected);},{},{timeout:20000});
 console.log(JSON.stringify({passed:true,checks:['shared persistent client','duplicate tab gets distinct slot','independent selections','refresh retains selection and slot but replaces live ID','dirty/edit reports','rename','restart reconnect preserves live ID and dirty state','paused lifecycle','closed tab disconnects']}));
}catch(e){for(const context of browser?.contexts()||[])for(const page of context.pages())console.error(await page.evaluate(()=>({report:window.dashboardReport,registration:window.talia?.registration(),error:document.querySelector("#diagnostic")?.textContent})));throw e;}finally{await browser?.close();if(server){server.kill('SIGTERM');await once(server,'exit');}if(engine?.exitCode===null){engine.kill('SIGTERM');await once(engine,'exit');}await rm(temp,{recursive:true,force:true});}
