import {chromium} from '../../spikes/runtime/node_modules/playwright/index.mjs';import {spawn} from 'node:child_process';import {once} from 'node:events';import {mkdtemp,readFile,writeFile,rm} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';
const temp=await mkdtemp(path.join(os.tmpdir(),'talia-definitions-')),file=path.join(temp,'package.json');const pkg=JSON.parse(await readFile('dashboard/generated/monitor.json','utf8'));await writeFile(file,JSON.stringify(pkg));
const server=spawn('python3',['dashboard/serve.py','0',file],{stdio:['ignore','pipe','inherit']});let browser,page;
try{
 const {port}=JSON.parse(String((await once(server.stdout,'data'))[0]));browser=await chromium.launch({headless:true});page=await browser.newPage();await page.goto(`http://127.0.0.1:${port}`);await page.waitForFunction(()=>window.dashboardReport?.state.history.length>0);
 await page.getByRole('button',{name:'Controls',exact:true}).click();await page.getByRole('button',{name:'Apply value',exact:true}).click();await page.waitForFunction(()=>dashboardReport.actions.some(a=>a.status==='completed'));
 await page.evaluate(()=>talia.live("TaliaVM.replaceAction('overview',c=>{const s=c.state();c.commit(s,{...s.value,screen:'overviewScreen',details:false});});"));await page.waitForFunction(()=>dashboardReport.dirty);
 await page.getByRole('button',{name:'Overview',exact:true}).click();await page.waitForFunction(()=>dashboardReport.state.details===false);assert.equal(await page.evaluate(()=>dashboardReport.state.details),false);
 const updated=structuredClone(pkg);updated.revision='revision-2';updated.definitions.notice.props.text='Updated shared notice';await writeFile(file,JSON.stringify(updated));
 await page.evaluate(()=>talia.checkUpdates());await page.locator('#update').waitFor();assert.equal(await page.evaluate(()=>dashboardReport.revision),pkg.revision);assert.equal(await page.getByText('Talìa · monitoring',{exact:true}).count(),1);
 await page.locator('#reload').click();await page.waitForFunction(()=>dashboardReport.revision==='revision-2'&&!dashboardReport.dirty&&dashboardReport.state.history.includes(25));
 await page.getByText('Updated shared notice',{exact:true}).waitFor();await page.getByRole('button',{name:'Controls',exact:true}).click();await page.getByText('Updated shared notice',{exact:true}).waitFor();assert.equal(await page.evaluate(()=>dashboardReport.state.details),true);
 await page.evaluate(()=>talia.live("throw Error('internal test failure')"));await page.getByRole('button',{name:'Restart dashboard',exact:true}).waitFor();assert.match(await page.locator('#diagnostic').textContent(),/Dashboard stopped/);
 await page.getByRole('button',{name:'Restart dashboard',exact:true}).click();await page.waitForFunction(()=>!dashboardReport.failure&&!dashboardReport.dirty&&dashboardReport.state.history.includes(25));
 const selected=structuredClone(updated);selected.id='secondary';selected.revision='client-selection';await writeFile(file,JSON.stringify(selected));await page.evaluate(()=>talia.selectDashboard('secondary'));await page.waitForFunction(()=>dashboardReport.client.dashboardId==='secondary'&&dashboardReport.revision==='client-selection');await page.reload();await page.waitForFunction(()=>window.dashboardReport?.client.dashboardId==='secondary'&&dashboardReport?.state.history.length>0);
 console.log(JSON.stringify({passed:true,checks:['independent persisted client dashboard selection','shared definition used by separate instances','update available without hot adoption','explicit reload adopts saved revision','dirty VM discarded','server effect retained','visible internal failure and manual restart'],revision:await page.evaluate(()=>dashboardReport.revision)}));
}catch(e){console.error(await page?.evaluate(()=>({error:document.querySelector('#diagnostic')?.textContent,report:window.dashboardReport})));throw e;}
finally{await browser?.close();server.kill('SIGTERM');await once(server,'exit');await rm(temp,{recursive:true,force:true});}
